spring:
    config:
        activate:
            on-profile: "db-local,db-test"
    datasource:
        url: jdbc:h2:tcp://localhost/~/skkubloodline
        username: sa
        password:
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                #show_sql: true
    h2:
        console:
            enabled: true
            settings:
                web-allow-others: true  # 추가

logging:
    level:
      org.hibernate.sql: debug

---
spring:
    config:
        activate:
            on-profile: "db-dev"
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://skku-bloodline-db.czzz43eadl5o.ap-northeast-2.rds.amazonaws.com/skku_bloodline?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
        username: admin
        password: qwer1234
    jpa:
        database-platform: org.hibernate.dialect.MySQL57Dialect
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
logging:
    level:
        org.hibernate.sql: debug