on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  push-test:
    name: push and build test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
       
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17 
